### PR TITLE
Added ETC compression

### PR DESCRIPTION
**Pull request by devjn**
Needs some polishing. Compression types are not updated from Model

### CODE REVIEW

**Comment by metaphore** [comment]
Thanks a lot for the PR, looks like you did a great job on this compression integration.
Unfortunately, I have zero experience with memory level compression and I will certainly need a little time to cover this topic before we can shape this and make a new release.

Can you please answer next questions to help me step into this a bit faster:
1. Do we still need custom `KTXProcessor` class or we can fully replace it with the original one from LibGDX 1.9.6?
2. Does `KTXProcessor` work only with `png` files and has no support for `jpg`?
3. Is there any (significant) impact on `ktx` file size from previously compressed `png` file?
4. If we simply replace `page.png` with generated `page.ktx` inside `.atlas` file, then `TextureAtlas` can be instantiated from it and work just fine, correct?

**Comment by devjn** [comment]
What do you mean by experience with memory level compression?

1. Well, I made a PR (which I need now to update again) to Libgdx, but I don't know if they will except it. Moreover `KTXProcessor ` runs as Headless app which doesn't look good, so I decided to modify it.
2. I think it works with any texture type, but not sure.
3. I am not sure about it, but I think that i decompress it and then compress to `ktx`, so I doubt about it.
4. Yes, this should work.

**Comment by metaphore** [comment]
I meant that I never used ETC or any other compression of that kind, so it's a bit hard for me now.
1. Then it's better stick to the custom class for now.
2. I've been thinking about to cut `jpg` support completely. Because for me it's a pretty strange solution to store atlases in this format, `jpg` distortion level too big and may corrupt adjacent region edges sometimes. So now, if there will be a choice between `jpg` or `etc`, I would rather go with only second one.
3. I'm just curious if we still should keep `png` and `etc` compressions in a separate lists. Because if there no difference in how hard `png` was compressed before turned into `ktx, than probably we can make `ktx` file right after `PackingProcessor` has done its job.

**Comment by devjn** [comment]
Oh, okay. I think you may ask me if you will need.
1. Yes, maybe in future it will be eventually possible to use original one.
2. Yeah, I think `jpg` is almost useless, but etctool can convert it.
3. Well, I just tested, files with different compression have same size of `ktx ` file. But I was thinking that sometimes you may need both types, so placed separately.

**Comment by metaphore** [comment]
Alright, thanks! So let's just keep things as they are.

**Comment by devjn** [comment]
Okay, I was also thinking about it before implementing but I was thinking that some may need several formats at the same time, so implemented like this. If you need help, I can probably help you.

**Comment by metaphore** [comment]
Hm, I never thought about multiple export options, it could be a good feature though. For now users can solve it by creating copies of existing packs and modify configuration. I will put this idea in backlog and once new configuration is done we can get back to it.

Thanks, but new configuration model code will likely require a lot of refactoring, so I better deal with it on myself.

**Pull request merged**
