### PR TITLE
Use Github API instead of plain openURL for crash reports

### PR DESCRIPTION
**Pull request by Naxos84**
Use github API to create issues.
See: https://developer.github.com/v3/guides/getting-started/

Using a java api:
https://github.com/eclipse/egit-github/tree/master/org.eclipse.egit.github.core

### CODE REVIEW

**Comment by Naxos84** [comment]
I not used to the Swing framework so please be patient and check the code carefully.

**Comment by metaphore** [comment]
Hey thanks, I also was looking into it yesterday and wanted to implement GitHub API for the next version. Will check it and get back to you!

**Comment by Naxos84** [comment]
It is possible to use a OAuth2 Token for login.
But I'm not sure wether the user that creates an issue really should need this.

**Comment by Naxos84** [comment]
Do you want everyone to be able to create an issue?
Or do you just want users with existing github accounts (or those that are willing to create one) to be able to create issues?

**Comment by metaphore** [comment]
No, I don't think that having a mutual account to post reports is a good idea, it should be the user himself who creates the issue, in order to have extra feedback otherwise issues could be bloated by nameless reports that repeat itself. Thus we still need to find the way to launch browser/webview and obtain OAuth2 token this way.

**Comment by Naxos84** [comment]
What about https://github.com/bertjan/google-oauth2-github-example/blob/master/src/main/java/nl/revolution/oauth2/example/RequestHandler.java

and

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

and

https://dzone.com/articles/how-to-implement-java-oauth-20-to-sign-in-with-git-1

There must be a way to set this up when combining these ways :D
I'm very new to all this stuff.

**Comment by metaphore** [comment]
Alright so, I finally managed to implement it in a proper way using [ScribeJava](https://github.com/scribejava/scribejava) and simple `HttpServer` on localhost to listen for GitHub OAuth2 browser callback. @Naxos84 thanks a lot for pointing me out mate, you made it a lot easier! If you're interesting in the details, check out [GitHubApiHelper.java](https://github.com/crashinvaders/gdx-texture-packer-gui/blob/29d5634e2ac7a0ffb40e4ecaae596bd76890dc1d/desktop/src/com/crashinvaders/texturepackergui/desktop/launchers/awt/errorreport/GitHubApiHelper.java).

**Comment by Naxos84** [comment]
Thats good news. Did you already plan a new release with the latest fixes?

**Comment by metaphore** [comment]
Yep, will roll it out tomorrow, if no more bugs will be spotted till then. Wednesday, 20 June 2018, 08:38AM +03:00 from Matthias  notifications@github.com :

**Pull request closed without merging**
