### PR TITLE
Updated to LibGDX 1.9.10.

### PR DESCRIPTION
**Pull request by shatterblast**
All dependencies were updated to the latest versions.  Gradle was updated to 5.4.1, so that it handles Java 11 and 12.

My simple tests seemed to work fine.  I did not test everything.  I tried exporting two series of .PNG files with RGBA4444 and no compression.  Everything worked fine on that end.

A Linux JAR file does not build and run correctly for me, but the app runs fine from within IntelliJ itself when compiled.  All other builds have not been tested either.

### CODE REVIEW

**Comment by metaphore** [comment]
Thanks for the PR! I'll review it in the next couple days.

**Comment by metaphore** [comment]
Hey @shatterblast, sorry it took so much time to review, been a bit busy.

It's all good in the first commit, but [the last one](https://github.com/crashinvaders/gdx-texture-packer-gui/pull/74/commits/3536100db26c1f9290149bc1e69d7461627c91a8) seems wrong in a way it kinda recreates all the projects files (there are 600+ changes).

I think I can just replicate the changes from the first one and include only those. What'd you say?

**Comment by shatterblast** [comment]
That's fine.

**Comment by metaphore** [comment]
Updated through [the commit](https://github.com/crashinvaders/gdx-texture-packer-gui/commit/942c27478818f1d73242a85ec31b5e13c139d2f2).

**Pull request closed without merging**
