### PR TITLE
Fix offsetY value when write pack file with setting `Strip Whitespace Y` checked

### PR DESCRIPTION
**Pull request by ani3llyon**
Expected rendered result:
ezgif-1-462241e23b

Actual rendered result:
ezgif-1-9aa3acb385

### CODE REVIEW

**Comment by metaphore** [comment]
Hi and thanks for the PR.

But I'm not sure if I understand your case right. So you try to pack a sprite sheet for animation. But why do you then use the "strip whitespace" feature? To me, it works exactly as expected - it removes empty space from the regions.
Am I missing something?

**Comment by ani3llyon** [comment]
First I want to pack a sprite sheet for animation,
and for the settings I do check options `Strip Whitespace X` and `Strip Whitespace Y`
Then I click `pack` button
after the pack process finished, there will be 2 files, one is a `xxx.png` and the other is `xxx.atlas`

For generated PNG file there is no issue,
but for the atlas file, I think there is something not right..

let's me confirm something first..
let say we have a atlas file with this content
```
soldier.png
size: 269, 78
format: RGBA8888
filter: Nearest, Nearest
repeat: none
...
soldier-attack
  rotate: false
  xy: 70, 51
  size: 19, 27
  orig: 100, 100
  offset: 41, 33
  index: 2
...
```

then if we map to the generated PNG file, it should be like following image right?
image

if my explanation above is right
Then if I pack included an image below
image

Then it should be included this following somewhere in the atlas file
```
soldier-attack
  rotate: false
  xy: [x], [x]
  size: 19, 27
  orig: 100, 100
  offset: 41, 33
  index: -1
```
but because the code to generate atlas file use below code to calculate the offset Y
```
int offsetY = rect.originalHeight - rect.regionHeight - rect.offsetY;
```

so what we found is
```
soldier-attack
  rotate: false
  xy: [x], [x]
  size: 19, 27
  orig: 100, 100
  offset: 41, 48 <~ calculate offset Y
  index: -1
```

```
// Following code is used to calculate offset Y from the bottom of image
int offsetY = rect.originalHeight - rect.regionHeight - rect.offsetY;
```

Well, if this is how the code is expected working, then you can close this PR..
and I will custom my code to work with this code..
Thanks for your response

**Comment by metaphore** [comment]
Thanks for the detailed example. But I believe there's a mistake in your image.

The actual area where the region is located in the PNG file is exactly the values of "xy" and "size". And the "orig" and "offset" fields are here just for the use case you described - when the app expects the regions to be of the original size and you need to shift the render position to compensate for it.

Have a look at this [test project](https://github.com/user-attachments/files/16592931/strips_ws_test0.zip). There's a single 32x32 image, which has content only in the central 16x16 area (8 pixels from each side should be trimmed as whitespace).
The atlas region data:
```
frame0
  rotate: false
  xy: 2, 2
  size: 16, 16
  orig: 32, 32
  offset: 8, 8
  index: -1
```
So the layout would look like this:
image

I should say, that I didn't test it in an actual libGDX project, but as far as I remember, most if not all libGDX image/sprite/scene2d classes simply ignore the `orig`/`offset` values. They just lay out a region as if the `size` is the actual size of the image. Plain and simple. The same is true for the animation classes. If you have inconsistent frame size you get this shaking effect and it's correct due to how the code is designed to work - with a spire sheet and not with an atlas.

But again, it looks like the offset is calculated correctly, there's no bug there. And if you really want to pack the frames tightly with the trim whitespace feature, you would need to do a little code work to translate from the packed size to the original size of the image wherever you do the rendering for those frames.

**Comment by Frosty-J** [comment]
Normally you can use `AtlasRegion` or `AtlasSprite` to automatically apply offsets/rotation. There's atlas versions for Scene2D drawable classes in the Discord server but these haven't been submitted to libGDX itself.

**Comment by ani3llyon** [comment]
Just check the source code of GDX..
My Bad, let me close this PR
image

**Pull request closed without merging**
